name: Test
on:
  push:
  pull_request:
    paths:
      - '**.js'

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install packages
        run: pacman --sync --nodeps --needed --noconfirm --refresh --sysupgrade curl mpv nodejs-lts-gallium npm
      - name: Show versions
        run: |
            curl --version
            mpv --version
            node --version
      - name: Install npm packages
        run: npm install
      - name: Run test
        run: npm test
  test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: Install packages
        run: |
            brew update
            brew install mpv
            brew upgrade
      - name: Show versions
        run: |
            curl --version
            mpv --version
            node --version
      - name: Install npm packages
        run: npm install
      - name: Run test
        run: npm test
  test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: Add scoop path to PATH environment variable
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: C:\scoop\shims;$env:PATH
      - name: Install scoop
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin -ScoopDir C:\scoop"
      - name: Setting scoop
        run: |
            scoop config debug $true
            scoop config aria2-enabled $true
            scoop bucket add extras
      - name: Install packages
        run: |
            scoop install aria2
            scoop install mpv
      - name: Show versions
        run: |
            curl.exe --version
            mpv.com --version
            node.exe --version
      - name: Install npm packages
        run: npm install
      - name: Run test
        run: npm test
